### ISSUE TITLE
Satellite Radio does not recover from TweeSlee

### ISSUE THREAD

**Issue by lcongdon** [silver-sat/Radio_Software#4]
With the experimental Radio code, sending a TweeSlee, the satellite Radio disconnects and reconnects on the debug port. It is unresponsive to ground commands transmitted by the ground Radio. After it processes a beacon it seems fine. If beacons are turned off, it does not recover.

**Comment by tconrad26** [comment]
I have seen occasional 'bad scratch value' returned from ax_init.  I was not checking the return value of ax_init, so if it did encounter a bad scratch value (probably because the chip reset was not complete), then it would drop out and not actually reset the radio properly.  I've modified all instances of ax_init to be within a while statement that loops until it properly resets the chip.

**Comment by lcongdon** [comment]
Ground software now looping showing:

E: Bad scratch value
N: Scratch 0xFF

repeatedly

**Comment by tconrad26** [comment]
Newest code includes check on ax_init when radio.begin is executed.
